# Generated by Django 6.1.1 on 2026-09-22 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pre_period_days', models.IntegerField(default=14, help_text='Days before promo for baseline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'promo',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PromoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promos', to='core.product')),
                ('product_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promos', to='core.productgroup')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_products', to='promos.promo')),
            ],
            options={
                'db_table': 'promo_product',
                'ordering': ['promo'],
            },
        ),
        migrations.CreateModel(
            name='PromoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField()),
                ('actual_sales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('baseline_pre_period', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('baseline_yoy', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('forecast_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='promos.promo')),
            ],
            options={
                'db_table': 'promo_analysis',
                'ordering': ['promo', 'analysis_date'],
                'unique_together': {('promo', 'analysis_date')},
            },
        ),
    ]
