# Generated by Django 5.2.17 on 2026-10-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='channels',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='promo',
            name='format',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='promo',
            name='promo_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='promoproduct',
            name='manual_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
