# Generated by Django 5.2.17 on 2026-10-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productgroup_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='kind',
            field=models.CharField(choices=[('group', 'Receipt group (STORGRP)'), ('warehouse', 'Warehouse (STORLIST)')], default='group', max_length=10),
        ),
    ]
