# Generated by Django 5.2.17 on 2026-10-08 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_store_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='GranitWpMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_product_id', models.CharField(max_length=32, unique=True)),
                ('granit_id', models.IntegerField(db_index=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'granit_wp_mapping',
                'ordering': ['wp_product_id'],
            },
        ),
        migrations.CreateModel(
            name='SiteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_product_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('last_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('avg_cost_90d', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('stock_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshots', to='core.product')),
            ],
            options={
                'db_table': 'product_cost_snapshot',
                'ordering': ['-snapshot_date', 'product_id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'snapshot_date'), name='product_cost_snapshot_uniq')],
            },
        ),
    ]
