# Generated by Django 5.2.18 on 2026-10-08 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_promo_control_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_category_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.CharField(blank=True, max_length=300)),
                ('count', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.sitecategory')),
            ],
            options={
                'db_table': 'site_category',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='siteproduct',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.sitecategory'),
        ),
    ]
