# Generated by Django 6.1.1 on 2026-09-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETLRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('etl_type', models.CharField(help_text='Type: incremental, backfill, dimensions', max_length=50)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_inserted', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('log_details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'etl_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ETLWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(help_text='Entity: sales, stock, etc', max_length=50, unique=True)),
                ('last_processed_date', models.DateField(blank=True, null=True)),
                ('last_processed_id', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'etl_watermark',
                'ordering': ['entity_name'],
            },
        ),
    ]
