# Generated by Django 6.1.1 on 2026-09-22 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='campaigns/')),
                ('analysis_period_start', models.DateField(blank=True, null=True)),
                ('analysis_period_end', models.DateField(blank=True, null=True)),
                ('total_clients', models.IntegerField(default=0)),
                ('clients_with_sales', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granit_client_id', models.IntegerField(help_text='Client ID from uploaded Excel')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('had_sales', models.BooleanField(default=False)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_clients', to='campaigns.campaign')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='core.client')),
            ],
            options={
                'db_table': 'campaign_client',
                'ordering': ['campaign', 'granit_client_id'],
                'unique_together': {('campaign', 'granit_client_id')},
            },
        ),
    ]
