# Generated by Django 6.1.1 on 2026-09-22 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(db_index=True, help_text='Date of sale')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity sold', max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Sale amount (money)', max_digits=15)),
                ('granit_sale_id', models.IntegerField(help_text='Sale document ID from Granit ERP', null=True)),
                ('granit_line_id', models.IntegerField(help_text='Sale line ID from Granit ERP', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.store')),
            ],
            options={
                'db_table': 'fact_sale',
                'ordering': ['-sale_date', 'store', 'product'],
                'indexes': [models.Index(fields=['sale_date', 'store'], name='fact_sale_sale_da_09e6c9_idx'), models.Index(fields=['sale_date', 'product'], name='fact_sale_sale_da_8c576e_idx'), models.Index(fields=['sale_date', 'client'], name='fact_sale_sale_da_1e5e55_idx'), models.Index(fields=['granit_sale_id', 'granit_line_id'], name='fact_sale_granit__85d18e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, help_text='Date of snapshot (yesterday)')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Stock quantity', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_snapshots', to='core.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_snapshots', to='core.store')),
            ],
            options={
                'db_table': 'fact_stock_snapshot',
                'ordering': ['-snapshot_date', 'store', 'product'],
                'indexes': [models.Index(fields=['snapshot_date', 'product'], name='fact_stock__snapsho_b8376f_idx')],
                'unique_together': {('snapshot_date', 'store', 'product')},
            },
        ),
    ]
