# Generated by Django 5.2.17 on 2026-10-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_store_kind'),
        ('sales', '0003_supergroup'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salefact',
            name='fact_sale_granit_line_uniq',
        ),
        migrations.AddField(
            model_name='salefact',
            name='source',
            field=models.CharField(choices=[('receipt', 'Cash-register receipt (STORZAKAZDT)'), ('invoice', 'Sales invoice (DGVDT)')], db_index=True, default='receipt', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='salefact',
            constraint=models.UniqueConstraint(fields=('source', 'granit_sale_id', 'granit_line_id'), name='fact_sale_source_line_uniq'),
        ),
    ]
